name: VBA FX Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii", "GameCube"]
    container: devkitpro/devkitppc:20250527

    steps:
    - name: Install packages
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 gamecube-tools-git libogc2 libogc2-libdvm

    - name: Checkout vbafx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j1

    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: |
        mkdir -p dist/VisualBoyAdvanceFX/apps/vbafx
        mkdir -p dist/VisualBoyAdvanceFX/vbafx/roms
        mkdir dist/VisualBoyAdvanceFX/vbafx/saves
        touch dist/VisualBoyAdvanceFX/vbafx/roms/romsdir
        touch dist/VisualBoyAdvanceFX/vbafx/saves/savesdir
        cp hbc/* dist/VisualBoyAdvanceFX/apps/vbafx/
        cp executables/vbafx-wii.dol dist/VisualBoyAdvanceFX/apps/vbafx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with:
        name: VisualBoyAdvanceFX
        path: |
          dist/VisualBoyAdvanceFX/

    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j1

    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        mkdir -p dist/VisualBoyAdvanceFX-GameCube
        cp executables/vbafx-gc.dol dist/VisualBoyAdvanceFX-GameCube/

    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'GameCube' }}
      with:
        name: VisualBoyAdvanceFX-GameCube
        path: |
          dist/VisualBoyAdvanceFX-GameCube/

