name: VBA FX Build (Wii)

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["Wii"]
    container: ghcr.io/extremscorner/libogc2:20260411

    steps:
    - name: Checkout vbagx repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j1

    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: |
        mkdir -p dist/VisualBoyAdvanceFX/apps/vbafx
        mkdir -p dist/VisualBoyAdvanceFX/vbafx/roms
        mkdir dist/VisualBoyAdvanceFX/vbafx/saves
        touch dist/VisualBoyAdvanceFX/vbafx/roms/romsdir
        touch dist/VisualBoyAdvanceFX/vbafx/saves/savesdir
        cp hbc/* dist/VisualBoyAdvanceFX/apps/vbafx/
        cp executables/vbafx-wii.dol dist/VisualBoyAdvanceFX/apps/vbafx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v7
      if: ${{ matrix.image == 'Wii' }}
      with:
        name: VisualBoyAdvanceFX
        path: |
          dist/VisualBoyAdvanceFX/

